"""empty message

Revision ID: 40c0a1549eec
Revises: 3bea1373e506
Create Date: 2017-03-31 21:26:52.909451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c0a1549eec'
down_revision = '3bea1373e506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership_plan', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('membership_plan', sa.Column('interval_months', sa.Integer(), nullable=True))
    op.add_column('membership_plan', sa.Column('payment_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership_plan', 'payment_key')
    op.drop_column('membership_plan', 'interval_months')
    op.drop_column('membership_plan', 'description')
    # ### end Alembic commands ###
